name: UViT
channels:
  - conda-forge
  - defaults
  - huggingface
  - pytorch
dependencies:
- black
- cffi
- cmake
- datasets
- jupyter
- matplotlib
- mkl
- nb_conda
- numpy
- python=3.8
- pytorch
- pyyaml
- scikit-learn
- seaborn
- setuptools
- tqdm
- transformers